name: resx_to_json_example
description: Example project for using resx_to_json dart tool
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:

dev_dependencies:
  flutter_lints: ^1.0.0

resx_to_json:
  # The directory containing resx files. The path can be relative or absolute.
  source: C:\Users\Mazlum\source\repos\_MergeSoft\AsoGotin\AsoGotin\Properties
  
  # The directory where the generated json files will be saved in. The path can be relative or absolute.
  destination: assets/localization/

  # Indicates whether the keys in json files should be sorted alphabetically. (Optional, default: true)
  sort: true

  # The extension for the generated json files. For example `arb`. (Optional, default: 'json')
  extension: arb

  # Regex patterns for renaming resx files. (Optional)
  # Notice that the search is case-sensitive
  # <regex_pattern> => <replacement> 
  replacements: 
    - Resources\.resx => en.arb
    - Resources\.([a-z]+)\.resx => $1.arb # $1 is the 1. match group. e.g. Resources.de.resx is renamed to de.json